kind: pipeline
type: docker
name: default

shared:
  image: node
  volumes:
  - name: cache
    path: /cache

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: install
  image: node
  volumes:
  - name: cache
    path: /cache
  commands: 
  - npm i

- name: test
  image: node
  volumes:
  - name: cache
    path: /cache
  commands: 
  - npm test
  depends_on:
  - install

- name: build
  image: node
  volumes:
  - name: cache
    path: /cache
  commands: 
  - npm run build
  depends_on:
  - install

- name: push
  image: node
  volumes:
  - name: cache
    path: /cache
  commands: 
  - echo push
  depends_on:
  - test
  - build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host: 
      path: /tmp/cache
